spring:
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}   
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.5-flash

logging:
  level:
    org.springframework.security: DEBUG
    com.ai.recipe.auth_service: DEBUG
    com.ai.recipe.auth_service.config: TRACE
    com.ai.recipe.auth_service.controller: TRACE
jwt:
  secret: ${JWT_SECRET:c2VjdXJlLXRvcC1zZWNyZXQta2V5LTI1Ni1iaXRzLXNlY3VyZQ==}
  expiration-ms: 86400000 

server:
  port: 8080
